export interface GistUploadResult {
  gistId: string;
  gistUrl: string;
  colabUrl: string;
}

/**
 * Uploads a .ipynb notebook as a secret GitHub Gist owned by the configured
 * GITHUB_TOKEN account. Returns the gist ID and the corresponding Google
 * Colab URL.
 *
 * Note: GitHub no longer allows anonymous gist creation — a token with
 * `gist` scope is required.
 */
export async function uploadGist(
  notebookJson: string,
  filename: string,
): Promise<GistUploadResult> {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    throw new Error(
      "GITHUB_TOKEN is not configured — set a GitHub PAT with gist scope to enable Colab links.",
    );
  }

  const payload = {
    description: "Generated by paper-to-colab",
    public: false,
    files: {
      [filename]: {
        content: notebookJson,
      },
    },
  };

  const response = await fetch("https://api.github.com/gists", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    const message =
      (errorData as { message?: string }).message ?? "Unknown error";
    throw new Error(`GitHub Gist API error (${response.status}): ${message}`);
  }

  const data = (await response.json()) as {
    id: string;
    html_url: string;
  };

  const gistId = data.id;
  if (!/^[a-f0-9]+$/i.test(gistId)) {
    throw new Error(`Invalid gist ID received from GitHub API: "${gistId}"`);
  }

  const gistUrl = data.html_url;
  const colabUrl = `https://colab.research.google.com/gist/anonymous/${gistId}`;

  return { gistId, gistUrl, colabUrl };
}
