import { describe, it, expect, vi, beforeEach } from "vitest";
import { uploadGist } from "../../lib/uploadGist";

function mockFetchSuccess(id = "abc123def456", htmlUrl?: string) {
  return vi.fn().mockResolvedValueOnce({
    ok: true,
    json: async () => ({
      id,
      html_url: htmlUrl ?? `https://gist.github.com/${id}`,
    }),
  }) as unknown as typeof fetch;
}

function mockFetchError(status: number, message: string) {
  return vi.fn().mockResolvedValueOnce({
    ok: false,
    status,
    json: async () => ({ message }),
  }) as unknown as typeof fetch;
}

describe("uploadGist — payload structure", () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  it("sends public: false in the payload (secret gist)", async () => {
    const mockFn = mockFetchSuccess();
    global.fetch = mockFn;

    await uploadGist('{"nbformat":4}', "test.ipynb");

    const body = JSON.parse(mockFn.mock.calls[0][1].body);
    expect(body.public).toBe(false);
  });

  it("includes the filename as the gist file key", async () => {
    const mockFn = mockFetchSuccess();
    global.fetch = mockFn;

    await uploadGist('{"nbformat":4}', "my-notebook.ipynb");

    const body = JSON.parse(mockFn.mock.calls[0][1].body);
    expect(body.files["my-notebook.ipynb"]).toBeDefined();
    expect(body.files["my-notebook.ipynb"].content).toBe('{"nbformat":4}');
  });

  it("sets the description to 'Generated by paper-to-colab'", async () => {
    const mockFn = mockFetchSuccess();
    global.fetch = mockFn;

    await uploadGist('{"nbformat":4}', "test.ipynb");

    const body = JSON.parse(mockFn.mock.calls[0][1].body);
    expect(body.description).toBe("Generated by paper-to-colab");
  });

  it("sends Accept header for GitHub v3 API", async () => {
    const mockFn = mockFetchSuccess();
    global.fetch = mockFn;

    await uploadGist('{"nbformat":4}', "test.ipynb");

    const headers = mockFn.mock.calls[0][1].headers;
    expect(headers.Accept).toBe("application/vnd.github+json");
  });
});

describe("uploadGist — response handling", () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  it("returns gistId, gistUrl, and colabUrl on success", async () => {
    global.fetch = mockFetchSuccess("deadbeef1234");

    const result = await uploadGist('{}', "test.ipynb");

    expect(result.gistId).toBe("deadbeef1234");
    expect(result.gistUrl).toBe("https://gist.github.com/deadbeef1234");
    expect(result.colabUrl).toBe(
      "https://colab.research.google.com/gist/anonymous/deadbeef1234"
    );
  });

  it("throws on non-ok response with status and message", async () => {
    global.fetch = mockFetchError(422, "Validation Failed");

    await expect(uploadGist('{}', "test.ipynb")).rejects.toThrow(
      /GitHub Gist API error \(422\): Validation Failed/
    );
  });

  it("throws with 'Unknown error' when error response has no message", async () => {
    global.fetch = vi.fn().mockResolvedValueOnce({
      ok: false,
      status: 500,
      json: async () => ({}),
    }) as unknown as typeof fetch;

    await expect(uploadGist('{}', "test.ipynb")).rejects.toThrow(
      /Unknown error/
    );
  });

  it("throws with 'Unknown error' when error response JSON parsing fails", async () => {
    global.fetch = vi.fn().mockResolvedValueOnce({
      ok: false,
      status: 500,
      json: async () => { throw new Error("bad json"); },
    }) as unknown as typeof fetch;

    await expect(uploadGist('{}', "test.ipynb")).rejects.toThrow(
      /Unknown error/
    );
  });
});

describe("uploadGist — gistId validation", () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  it("accepts valid hex gist IDs", async () => {
    global.fetch = mockFetchSuccess("abcdef0123456789");
    const result = await uploadGist('{}', "test.ipynb");
    expect(result.gistId).toBe("abcdef0123456789");
  });

  it("rejects gist ID with path traversal characters", async () => {
    global.fetch = vi.fn().mockResolvedValueOnce({
      ok: true,
      json: async () => ({
        id: "../../../etc/passwd",
        html_url: "https://gist.github.com/x",
      }),
    }) as unknown as typeof fetch;

    await expect(uploadGist('{}', "test.ipynb")).rejects.toThrow(
      /Invalid gist ID/
    );
  });

  it("rejects gist ID with spaces", async () => {
    global.fetch = vi.fn().mockResolvedValueOnce({
      ok: true,
      json: async () => ({
        id: "abc 123",
        html_url: "https://gist.github.com/x",
      }),
    }) as unknown as typeof fetch;

    await expect(uploadGist('{}', "test.ipynb")).rejects.toThrow(
      /Invalid gist ID/
    );
  });

  it("accepts uppercase hex characters in gist ID", async () => {
    global.fetch = mockFetchSuccess("ABCDEF0123456789");
    const result = await uploadGist('{}', "test.ipynb");
    expect(result.gistId).toBe("ABCDEF0123456789");
  });
});
